#!/bin/bash

kubectl delete configmap -n management jumpserver-internal

kubectl create configmap -n management jumpserver-internal \
  --from-file=tmux-config=./files/.tmux.conf \
  --from-file=authorized-keys=./files/authorized_keys
